import { useEffect, useState } from 'react'; import api from '../api/client';
const emptyPolicy = { name: '', type: 'HEALTH', description: '', premium: '', coverageAmount: '', termMonths: 12 };
const emptyUser = { name: '', email: '', password: '', role: 'AGENT', phone: '', address: '' };
export default function Admin() {
    const [stats, setStats] = useState({}); const [users, setUsers] = useState([]); const [policies, setPolicies] = useState([]); const [claims, setClaims] = useState([]); const [policy, setPolicy] = useState(emptyPolicy); const [user, setUser] = useState(emptyUser); const [editingPolicy, setEditingPolicy] = useState(null); const [editingUser, setEditingUser] = useState(null); const [roleFilter, setRoleFilter] = useState('ALL'); const [notice, setNotice] = useState('');
    const load = () => { api.get('/dashboard/summary').then(r => setStats(r.data)); api.get('/users').then(r => setUsers(r.data)); api.get('/policies').then(r => setPolicies(r.data)); api.get('/claims').then(r => setClaims(r.data)) }; useEffect(load, []);
    const message = e => setNotice(e.response?.data?.message || 'Request failed');
    const savePolicy = async e => { e.preventDefault(); try { const body = { ...policy, premium: Number(policy.premium), coverageAmount: Number(policy.coverageAmount), termMonths: Number(policy.termMonths) }; if (editingPolicy) await api.put(`/policies/${editingPolicy}`, body); else await api.post('/policies', body); setPolicy(emptyPolicy); setEditingPolicy(null); setNotice(editingPolicy ? 'Policy updated.' : 'Policy created.'); load() } catch (e) { message(e) } };
    const removePolicy = async id => { if (!window.confirm('Delete this policy?')) return; try { await api.delete(`/policies/${id}`); setNotice('Policy deleted.'); load() } catch (e) { message(e) } };
    const saveUser = async e => { e.preventDefault(); try { const body = { ...user }; if (editingUser && !body.password) delete body.password; if (editingUser) await api.put(`/users/${editingUser}`, body); else await api.post('/users', body); setUser(emptyUser); setEditingUser(null); setNotice(editingUser ? 'User updated.' : 'User created.'); load() } catch (e) { message(e) } };
    const removeUser = async id => { if (!window.confirm('Delete this user?')) return; try { await api.delete(`/users/${id}`); setNotice('User deleted.'); load() } catch (e) { message(e) } };
    const visibleUsers = roleFilter === 'ALL' ? users : users.filter(x => x.role === roleFilter);
    return <><div className="page-title"><div><span className="eyebrow">ADMIN</span><h1>Administration</h1><p>Manage policies, customers, agents and operations.</p></div></div>{notice && <div className="alert">{notice}</div>}<div className="cards">{[['Customers', stats.customers], ['Agents', stats.agents], ['Policies', stats.policies], ['Pending claims', stats.pendingClaims], ['Paid premiums', `₹${Number(stats.paidPremiums || 0).toLocaleString('en-IN')}`], ['Payments', stats.payments]].map(x => <div className="stat" key={x[0]}><span>{x[0]}</span><strong>{x[1] || 0}</strong></div>)}</div>
        <section className="panel"><div className="panel-head"><h2>{editingPolicy ? 'Edit policy' : 'Create policy'}</h2>{editingPolicy && <button className="ghost" type="button" onClick={() => { setEditingPolicy(null); setPolicy(emptyPolicy) }}>Cancel</button>}</div><form onSubmit={savePolicy} className="grid2"><label>Name<input required value={policy.name} onChange={e => setPolicy({ ...policy, name: e.target.value })} /></label><label>Type<select value={policy.type} onChange={e => setPolicy({ ...policy, type: e.target.value })}><option>LIFE</option><option>HEALTH</option><option>MOTOR</option><option>HOME</option><option>TRAVEL</option></select></label><label>Premium<input type="number" min="1" required value={policy.premium} onChange={e => setPolicy({ ...policy, premium: e.target.value })} /></label><label>Coverage<input type="number" min="1" required value={policy.coverageAmount} onChange={e => setPolicy({ ...policy, coverageAmount: e.target.value })} /></label><label>Term months<input type="number" min="1" required value={policy.termMonths} onChange={e => setPolicy({ ...policy, termMonths: e.target.value })} /></label><label className="span2">Description<textarea value={policy.description} onChange={e => setPolicy({ ...policy, description: e.target.value })} /></label><button className="btn span2">{editingPolicy ? 'Update policy' : 'Create policy'}</button></form><div className="table-wrap"><table><thead><tr><th>Policy</th><th>Type</th><th>Premium</th><th>Status</th><th>Actions</th></tr></thead><tbody>{policies.map(p => <tr key={p.id}><td>{p.name}</td><td>{p.type}</td><td>₹{Number(p.premium).toLocaleString('en-IN')}</td><td>{p.status}</td><td><button className="ghost" onClick={() => { setEditingPolicy(p.id); setPolicy({ name: p.name, type: p.type, description: p.description || '', premium: p.premium, coverageAmount: p.coverageAmount, termMonths: p.termMonths }) }}>Edit</button>{!p.customer && <button className="ghost" onClick={() => removePolicy(p.id)}>Delete</button>}</td></tr>)}</tbody></table></div></section>
        <section className="panel"><div className="panel-head"><h2>{editingUser ? 'Edit user' : 'Add agent or customer'}</h2><select value={roleFilter} onChange={e => setRoleFilter(e.target.value)}><option value="ALL">All users</option><option value="AGENT">Agents</option><option value="CUSTOMER">Customers</option><option value="ADMIN">Admins</option></select></div><form onSubmit={saveUser} className="grid2"><label>Name<input required value={user.name} onChange={e => setUser({ ...user, name: e.target.value })} /></label><label>Email<input type="email" required value={user.email} onChange={e => setUser({ ...user, email: e.target.value })} /></label><label>Password<input type="password" minLength="6" required={!editingUser} value={user.password} onChange={e => setUser({ ...user, password: e.target.value })} /></label><label>Role<select value={user.role} onChange={e => setUser({ ...user, role: e.target.value })}><option>AGENT</option><option>CUSTOMER</option><option>ADMIN</option></select></label><label>Phone<input value={user.phone} onChange={e => setUser({ ...user, phone: e.target.value })} /></label><label>Address<input value={user.address} onChange={e => setUser({ ...user, address: e.target.value })} /></label><button className="btn">{editingUser ? 'Update user' : 'Add user'}</button>{editingUser && <button className="ghost" type="button" onClick={() => { setEditingUser(null); setUser(emptyUser) }}>Cancel</button>}</form><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{visibleUsers.map(u => <tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td><td><button className="ghost" onClick={() => { setEditingUser(u.id); setUser({ name: u.name, email: u.email, password: '', role: u.role, phone: u.phone || '', address: u.address || '' }) }}>Edit</button><button className="ghost" onClick={() => removeUser(u.id)}>Delete</button></td></tr>)}</tbody></table></div></section>
        <section className="panel"><h2>Claims overview</h2><div className="table-wrap"><table><thead><tr><th>Claim</th><th>Policy</th><th>Amount</th><th>Status</th></tr></thead><tbody>{claims.map(c => <tr key={c.id}><td>{c.claimNumber}</td><td>{c.policy?.name}</td><td>₹{Number(c.amount).toLocaleString('en-IN')}</td><td>{c.status}</td></tr>)}</tbody></table></div></section></>
}
